Vagrant.configure(2) do |config|

    vm_memory = ENV['VM_MEMORY'] || '6600'
    vm_cpus = ENV['VM_CPUS'] || '4'

    config.ssh.forward_agent = true
    config.vm.hostname = "devstack4"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    ## or use: vagrant ssh -- -L 0.0.0.0:8080:localhost:80

    config.vm.network "private_network", ip: "192.168.51.10"
    ## config.vm.network "public_network",
    ##                  :dev => "bridge0",
    ##                  :mode => "bridge",
    ##                  :type => "bridge"
    config.vm.box = "centos/7"
    config.vm.synced_folder "#{ENV['PWD']}", "/vagrant", sshfs_opts_append: "-o nonempty", disabled: false, type: "sshfs"

    config.vm.provider 'libvirt' do |lb|
        lb.nested = true
        lb.memory = vm_memory
        lb.cpus = vm_cpus
        lb.suspend_mode = 'managedsave'
    end
    config.vm.provider "virtualbox" do |vb|
       vb.memory = vm_memory
       vb.cpus = vm_cpus
       vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
       vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
       vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
       vb.customize ['modifyvm', :id, "--nicpromisc2", "allow-all"]
       vb.customize [
           "guestproperty", "set", :id,
           "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000
          ]
    end

    config.vm.provision :shell do |shell|
        shell.privileged = true
        shell.path = 'baseProvision.sh'
    end

end
